#!/usr/bin/env ruby
# frozen_string_literal: true

# Generates model artifacts from doc/model/model.yml.
#
#   ruby tools/model_gen.rb --puml --mdj
#   ruby tools/model_gen.rb --all
#
# --puml  doc/model/<package>.puml, PlantUML source
# --mdj   doc/model/toml-merge.mdj, a StarUML project opened natively
#
# Every output is generated. Edit doc/model/model.yml and re-run.

require "yaml"
require "json"
require "digest"
require "base64"
require "fileutils"

ROOT = File.expand_path("..", __dir__)
SOURCE = File.join(ROOT, "doc", "model", "model.yml")
OUT_DIR = File.join(ROOT, "doc", "model")
BANNER = "GENERATED by tools/model_gen.rb from doc/model/model.yml. Do not edit."

def log(step, message)
  warn format("  %-9s %s", step, message)
end

# --- model source -----------------------------------------------------------

class Model
  attr_reader :project, :packages

  def initialize(raw)
    @project = raw.fetch("project")
    @packages = raw.fetch("packages")
    @index = {}
    @packages.each do |pkg|
      (pkg["classes"] || []).each { |c| @index[c.fetch("name")] = [pkg, :class, c] }
      (pkg["enums"] || []).each { |e| @index[e.fetch("name")] = [pkg, :enum, e] }
    end
  end

  def self.load(path)
    log("read", path.sub("#{ROOT}/", ""))
    new(YAML.load_file(path))
  end

  def known?(name) = @index.key?(name)
  def package_of(name) = @index[name]&.first
  def kind_of(name) = @index[name]&.at(1)
  def definition(name) = @index.fetch(name).at(2)

  def elements(pkg) = (pkg["classes"] || []) + (pkg["enums"] || [])

  # Names a package's relations point at that the package does not itself own.
  def foreign_names(pkg)
    owned = elements(pkg).map { |e| e.fetch("name") }.to_set
    names = []
    (pkg["relations"] || []).each do |rel|
      names << rel.fetch("from") << rel.fetch("to")
    end
    elements(pkg).each do |el|
      (el["attributes"] || []).each { |a| names << a["type"] }
      (el["operations"] || []).each do |op|
        names << op["returns"]
        (op["params"] || []).each { |p| names << p["type"] }
      end
    end
    names.compact.uniq.reject { |n| owned.include?(n) }.select { |n| known?(n) }
  end
end

require "set"

# --- PlantUML ---------------------------------------------------------------

module Puml
  module_function

  def emit(model)
    model.packages.reject { |p| p["external"] }.map do |pkg|
      path = File.join(OUT_DIR, "#{pkg.fetch('name')}.puml")
      log("puml", "#{pkg.fetch('name')} -> #{path.sub("#{ROOT}/", '')}")
      File.write(path, render(model, pkg))
      path
    end
  end

  def render(model, pkg)
    out = []
    out << "@startuml #{model.project}-#{pkg.fetch('name')}"
    out << "' #{BANNER}"
    out << "skinparam classAttributeIconSize 0"
    out << "hide empty members"
    out << "title #{model.project}: #{pkg.fetch('title')}"
    out << ""
    out << "package #{pkg.fetch('name')} {"
    model.elements(pkg).each { |el| out.concat(element(el).map { |l| "  #{l}" }) }
    out << "}"

    by_package = model.foreign_names(pkg).group_by { |n| model.package_of(n).fetch("name") }
    by_package.each do |name, members|
      out << ""
      out << "package #{name} <<external>> {"
      members.each { |m| out << "  #{model.kind_of(m) == :enum ? 'enum' : 'class'} #{m}" }
      out << "}"
    end

    out << ""
    (pkg["relations"] || []).each { |rel| out << relation(rel) }
    out << "@enduml"
    "#{out.join("\n")}\n"
  end

  def element(el)
    return enum(el) if el.key?("literals")

    head = el["abstract"] ? "abstract class" : "class"
    head += " #{el.fetch('name')}"
    head += " <<#{el['stereotype']}>>" if el["stereotype"]
    body = []
    (el["attributes"] || []).each { |a| body << "  #{attribute(a)}" }
    ops = el["operations"] || []
    body << "  --" if body.any? && ops.any?
    ops.each { |o| body << "  #{operation(o)}" }
    doc = el["doc"] ? ["' #{el['doc'].strip.gsub(/\s+/, ' ')}"] : []
    doc + ["#{head} {"] + body + ["}"]
  end

  def enum(el)
    ["enum #{el.fetch('name')} {"] + el.fetch("literals").map { |l| "  #{l}" } + ["}"]
  end

  def attribute(attr)
    text = "+ #{attr.fetch('name')} : #{attr.fetch('type')}"
    text += " [#{attr['multiplicity']}]" if attr["multiplicity"]
    text += " = #{attr['default']}" if attr["default"]
    text
  end

  def operation(op)
    params = (op["params"] || []).map { |p| "#{p.fetch('name')} : #{p.fetch('type')}" }.join(", ")
    text = "+ "
    text += "{static} " if op["static"]
    text += "#{op.fetch('name')}(#{params})"
    text += " : #{op['returns']}" if op["returns"]
    text
  end

  def relation(rel)
    from = rel.fetch("from")
    to = rel.fetch("to")
    mult = rel["multiplicity"] ? " \"#{rel['multiplicity']}\"" : ""
    case rel.fetch("kind")
    when "generalization" then "#{from} --|> #{to}"
    when "composition"    then "#{from} *--#{mult} #{to} : #{rel['name']}"
    when "aggregation"    then "#{from} o--#{mult} #{to} : #{rel['name']}"
    when "dependency"     then "#{from} ..> #{to} : #{rel['label']}"
    else                       "#{from} -->#{mult} #{to} : #{rel['name']}"
    end
  end
end

# --- StarUML ----------------------------------------------------------------

module Mdj
  module_function

  # Grid layout. StarUML resizes a view up to its content on first repaint, so
  # these are starting sizes, not final ones.
  COLUMN_WIDTH = 320
  ROW_HEIGHT = 240
  ORIGIN = 48
  MIN_WIDTH = 140
  MAX_WIDTH = 460
  LINE_HEIGHT = 16
  HEADER_HEIGHT = 34

  # StarUML ids are opaque strings. Deriving them from the element path keeps
  # them stable across runs, so regenerating produces a readable diff.
  def id_for(path)
    Base64.strict_encode64(Digest::SHA1.digest(path)[0, 15])
  end

  def emit(model)
    path = File.join(OUT_DIR, "#{model.project}.mdj")
    log("mdj", "building project tree")
    File.write(path, "#{JSON.pretty_generate(project(model))}\n")
    log("mdj", "-> #{path.sub("#{ROOT}/", '')}")
    path
  end

  def project(model)
    project_id = id_for("project")
    model_id = id_for("model")
    {
      "_type" => "Project", "_id" => project_id, "name" => model.project,
      "ownedElements" => [{
        "_type" => "UMLModel", "_id" => model_id,
        "_parent" => { "$ref" => project_id }, "name" => model.project,
        "ownedElements" => model.packages.map { |pkg| package(model, pkg, model_id) }
      }]
    }
  end

  def package(model, pkg, parent_id)
    name = pkg.fetch("name")
    pkg_id = id_for("pkg:#{name}")
    log("mdj", "package #{name}")

    nodes = model.elements(pkg).to_h { |el| [el.fetch("name"), element(model, el, pkg_id)] }
    # A relationship belongs to its source element, matching its _parent.
    (pkg["relations"] || []).each do |rel|
      from = rel.fetch("from")
      owner = nodes[from]
      next log("mdj", "  skip relation, #{from} is not owned by #{name}") unless owner
      next log("mdj", "  skip relation, unknown #{rel.fetch('to')}") unless model.known?(rel.fetch("to"))

      (owner["ownedElements"] ||= []) << relationship(model, rel)
    end

    owned = nodes.values
    owned << diagram(model, pkg, pkg_id)
    node = {
      "_type" => "UMLPackage", "_id" => pkg_id,
      "_parent" => { "$ref" => parent_id }, "name" => name,
      "ownedElements" => owned
    }
    node["documentation"] = squash(pkg["doc"]) if pkg["doc"]
    node
  end

  # --- model elements -------------------------------------------------------

  def element(model, el, parent_id)
    return enumeration(el, parent_id) if el.key?("literals")

    name = el.fetch("name")
    eid = id_for("class:#{name}")
    node = {
      "_type" => "UMLClass", "_id" => eid,
      "_parent" => { "$ref" => parent_id }, "name" => name
    }
    node["documentation"] = squash(el["doc"]) if el["doc"]
    node["isAbstract"] = true if el["abstract"]
    node["stereotype"] = el["stereotype"] if el["stereotype"]
    attrs = (el["attributes"] || []).map { |a| attribute(model, a, eid, name) }
    ops = (el["operations"] || []).map { |o| operation(model, o, eid, name) }
    node["attributes"] = attrs if attrs.any?
    node["operations"] = ops if ops.any?
    log("mdj", "  class #{name} (#{attrs.size} attrs, #{ops.size} ops)")
    node
  end

  def enumeration(el, parent_id)
    name = el.fetch("name")
    eid = id_for("enum:#{name}")
    log("mdj", "  enum #{name} (#{el.fetch('literals').size} literals)")
    {
      "_type" => "UMLEnumeration", "_id" => eid,
      "_parent" => { "$ref" => parent_id }, "name" => name,
      "literals" => el.fetch("literals").map do |lit|
        {
          "_type" => "UMLEnumerationLiteral", "_id" => id_for("lit:#{name}.#{lit}"),
          "_parent" => { "$ref" => eid }, "name" => lit
        }
      end
    }
  end

  def type_ref(model, type)
    return nil if type.nil?

    model.known?(type) ? ref_of(model, type) : type
  end

  def attribute(model, attr, parent_id, owner)
    node = {
      "_type" => "UMLAttribute", "_id" => id_for("attr:#{owner}.#{attr.fetch('name')}"),
      "_parent" => { "$ref" => parent_id }, "name" => attr.fetch("name"),
      "type" => type_ref(model, attr.fetch("type"))
    }
    node["multiplicity"] = attr["multiplicity"] if attr["multiplicity"]
    node["defaultValue"] = attr["default"].to_s if attr["default"]
    node
  end

  def operation(model, op, parent_id, owner)
    name = op.fetch("name")
    oid = id_for("op:#{owner}.#{name}")
    params = (op["params"] || []).map do |p|
      {
        "_type" => "UMLParameter", "_id" => id_for("param:#{owner}.#{name}.#{p.fetch('name')}"),
        "_parent" => { "$ref" => oid }, "name" => p.fetch("name"),
        "type" => type_ref(model, p.fetch("type"))
      }
    end
    if op["returns"] && op["returns"] != "void"
      params << {
        "_type" => "UMLParameter", "_id" => id_for("param:#{owner}.#{name}.return"),
        "_parent" => { "$ref" => oid }, "name" => "",
        "type" => type_ref(model, op["returns"]), "direction" => "return"
      }
    end
    node = {
      "_type" => "UMLOperation", "_id" => oid,
      "_parent" => { "$ref" => parent_id }, "name" => name
    }
    node["isStatic"] = true if op["static"]
    node["isQuery"] = true if op["query"]
    node["parameters"] = params if params.any?
    node
  end

  def relationship(model, rel)
    from = rel.fetch("from")
    to = rel.fetch("to")
    source = ref_of(model, from)
    target = ref_of(model, to)
    rid = relationship_id(rel)
    case rel.fetch("kind")
    when "generalization"
      {
        "_type" => "UMLGeneralization", "_id" => rid,
        "_parent" => source, "source" => source, "target" => target
      }
    when "dependency"
      node = {
        "_type" => "UMLDependency", "_id" => rid,
        "_parent" => source, "source" => source, "target" => target
      }
      node["name"] = rel["label"] if rel["label"]
      node
    else
      association(rel, rid, source, target)
    end
  end

  def association(rel, rid, source, target)
    aggregation = case rel.fetch("kind")
                  when "composition" then "composite"
                  when "aggregation" then "shared"
                  else "none"
                  end
    {
      "_type" => "UMLAssociation", "_id" => rid, "_parent" => source,
      "end1" => {
        "_type" => "UMLAssociationEnd", "_id" => "#{rid}1",
        "_parent" => { "$ref" => rid }, "reference" => source,
        "aggregation" => aggregation
      },
      "end2" => {
        "_type" => "UMLAssociationEnd", "_id" => "#{rid}2",
        "_parent" => { "$ref" => rid }, "reference" => target,
        "name" => rel["name"].to_s, "multiplicity" => rel["multiplicity"].to_s,
        "navigable" => "navigable"
      }
    }
  end

  def relationship_id(rel)
    id_for("rel:#{rel.fetch('kind')}:#{rel.fetch('from')}:#{rel.fetch('to')}:#{rel['name']}#{rel['label']}")
  end

  # --- diagram views --------------------------------------------------------

  # A view carries geometry only. UMLClassifierView's constructor builds the
  # name, attribute, operation, reception and template compartments, and
  # Element#load appends what the file holds to what the constructor made, so
  # writing compartments here would duplicate them.
  def diagram(model, pkg, pkg_id)
    name = pkg.fetch("name")
    diagram_id = id_for("diagram:#{name}")
    shown = model.elements(pkg).map { |el| el.fetch("name") } + model.foreign_names(pkg)
    placed = place(model, shown, name, diagram_id)
    edges = (pkg["relations"] || []).filter_map { |rel| edge_view(model, rel, placed, diagram_id) }
    log("mdj", "  diagram #{name} (#{placed.size} nodes, #{edges.size} edges)")
    {
      "_type" => "UMLClassDiagram", "_id" => diagram_id,
      "_parent" => { "$ref" => pkg_id }, "name" => pkg.fetch("title", name),
      "visible" => true, "defaultDiagram" => name == model.packages.first["name"],
      "ownedViews" => placed.values + edges
    }
  end

  def place(model, names, pkg_name, diagram_id)
    columns = Math.sqrt(names.size).ceil
    names.each_with_index.to_h do |element_name, i|
      width, height = view_size(model, element_name)
      view = {
        "_type" => model.kind_of(element_name) == :enum ? "UMLEnumerationView" : "UMLClassView",
        "_id" => id_for("view:#{pkg_name}:#{element_name}"),
        "_parent" => { "$ref" => diagram_id },
        "model" => ref_of(model, element_name),
        "left" => ORIGIN + (i % columns) * COLUMN_WIDTH,
        "top" => ORIGIN + (i / columns) * ROW_HEIGHT,
        "width" => width, "height" => height
      }
      [element_name, view]
    end
  end

  def view_size(model, name)
    el = model.definition(name)
    return [MIN_WIDTH, HEADER_HEIGHT + LINE_HEIGHT * el.fetch("literals").size] if el.key?("literals")

    members = (el["attributes"] || []).map { |a| Puml.attribute(a) } +
              (el["operations"] || []).map { |o| Puml.operation(o) }
    widest = ([name.length] + members.map(&:length)).max
    width = (widest * 7 + 28).clamp(MIN_WIDTH, MAX_WIDTH)
    [width, HEADER_HEIGHT + LINE_HEIGHT * members.size + 8]
  end

  def edge_view(model, rel, placed, diagram_id)
    tail = placed[rel.fetch("from")]
    head = placed[rel.fetch("to")]
    return nil unless tail && head

    type = case rel.fetch("kind")
           when "generalization" then "UMLGeneralizationView"
           when "dependency" then "UMLDependencyView"
           else "UMLAssociationView"
           end
    {
      "_type" => type, "_id" => id_for("edgeview:#{diagram_id}:#{relationship_id(rel)}"),
      "_parent" => { "$ref" => diagram_id },
      "model" => { "$ref" => relationship_id(rel) },
      "tail" => { "$ref" => tail.fetch("_id") },
      "head" => { "$ref" => head.fetch("_id") }
    }
  end

  def ref_of(model, name)
    prefix = model.kind_of(name) == :enum ? "enum" : "class"
    { "$ref" => id_for("#{prefix}:#{name}") }
  end

  def squash(text) = text.strip.gsub(/\s+/, " ")
end

# --- entry point ------------------------------------------------------------

wanted = ARGV.empty? ? ["--all"] : ARGV
all = wanted.include?("--all")
FileUtils.mkdir_p(OUT_DIR)

warn "model_gen: #{SOURCE.sub("#{ROOT}/", '')}"
model = Model.load(SOURCE)
written = []
written.concat(Puml.emit(model)) if all || wanted.include?("--puml")
written << Mdj.emit(model) if all || wanted.include?("--mdj")
warn "model_gen: wrote #{written.size} file(s)"
